Migrate Ahnlich DB  to Grpc Implementation and Types (#200)
* Upgrading cargo to 1.85

* Unit type proto functions still need atleast one argument

* WIP: Adding stop gaps for moving listener stream

* Derive serde serialize and deserialize from prost files for db store

* WIP: swapping out ahnlich types from db store

* Migration: Complete swap in db (algorithm and similarity), store.rs 90% done..

* Migration: Complete store.rs swap to grpc types

* Migration: Complete swap in db -> predicate.rs

* Update handler to use grpc_types without a need for type conversions

* connect ahnlichserverutilsv2 to db Server struct

* Use grpc types in db benches

* Adding pipeline for DB client

* WIP: Migrating ai service to grpc

* WIP: ahnlich AI is building now

* format grpc types

* complete set command in db. Add type conversion froms storeinput to metadatavalue and the reverse

* Remove metadatatype from protos

* WIP: Migrate DB Tests: create store and del pred tests migrated

* Migration: Add all equivalent tests from server_test.rs. Remaining: persistence and connection limit

* Complete Persistence tests

* Fix client tracking without request layer

* Fixing lib from main

* remove server tests and fmt

* Fixing formatting

* Adding GRPC migration TODO

* Migrating DSL to use grpc types

* Ticked DSL task as done

* David/grpc migration (#201)

* Complete Fixmes in db

* port client db tests to grpc types

* port client ai tests to grpc types

* expect on server start on client db tests

* Select port for DB as the default is the same

* fxing test assertions for client

* Fix client db test assertions. Though it seems to be flaky when connecting to the db

* Fix typo

---------

Co-authored-by: Diretnan Domnan <diretnandomnan@gmail.com>

* More On Test Migrations (#202)

* WIP: ai_proxy tests migration

* Fix db_store_entry_to_store_get_key logic

* WIP: migrating AI tests.. 90%

* rewriting AI tests 99%

* fix error conversion for ahnlicherror

* fix persistence test error

* Update client docs and path to new ported clients

* Rename grpc_types to types

* More renaming from grpc_types to ahnlich_types

* Fix Ahnlich CLI

* Fix Rust Example

* Add lint directive for examples to workflow file

* Clippy fixes

* fixing path in action

* fix failing tests and sort list stores res

* formatting similarity

* fix tests in get key

* fix tests in get key

* Migrated python client to gRPC

* Adding CI checks for python and rust client

* Remove .DS_Store from py client

* Standardize ai del_key to take multiple keys

* WIP: migrating ahnlich python client readme

* Finish readme update chaning some imports error

* WIP: moving demo_embed to grpc impl

* Migrate demo embed to grpc types

* Migrate demo tracing example to grpc variant

* WIP: migrate book_search example in python: searchphrase issue to be resolvedd

* Fixing booksearch mixup with ai_query.StoreKey vs keyval.StoreKey

* Standardizing ai and db StoreEntry to be exact

---------

Co-authored-by: Diretnan Domnan <diretnandomnan@gmail.com>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -49,6 +49,21 @@ jobs:
         make format
         make clippy
 
+    - name: Check Rust Client is up to date
+      working-directory: ./ahnlich
+      run: |
+        make grpc-update-rust
+        if [[ -n "$(git status . --porcelain)" ]]; then
+          echo "::error::Running 'make grpc-update-rust' caused changes, Please check that rust client is up to date"
+          git --no-pager diff .
+          exit 1
+        fi
+
+    - name: Build and Format Rust Example
+      working-directory: ./examples/rust/image-search
+      run: |
+        cargo b && cargo fmt
+
     - name: Run Test
       working-directory: ./ahnlich
       run: |
@@ -101,6 +116,16 @@ jobs:
       working-directory: ./ahnlich
       run: |
         cargo build
+
+    - name: Check Python Client is up to date
+      working-directory: ./ahnlich
+      run: |
+        make grpc-update-python
+        if [[ -n "$(git status ../sdk/ahnlich-client-py --porcelain)" ]]; then
+          echo "::error::Running 'make grpc-update-python' caused changes, Please check that python client is up to date"
+          git --no-pager diff ../sdk/ahnlich-client-py
+          exit 1
+        fi
     
     - name: Run Python Client Tests
       working-directory: ./sdk/ahnlich-client-py
